### ISSUE TITLE
Some-Peripherals-0.0.12-fabric crashes on Minecraft 1.20.1

### ISSUE THREAD

**Issue by onehittoaster** [xiewuzhiying/Some-Peripherals#1]
With minimal mods installed (VS2, Create, CC: Tweaked, Fabric API, Fabric Kotlin API), the game crashes upon launch if `Some-Peripherals-0.0.12-fabric.jar` is installed.  We'd really like to use the Radar and a few other blocks on MC 1.20.1, Fabric.

```
.minecraft/mods $ ls *.jar | cat
architectury-9.2.14-fabric.jar
cc-tweaked-1.20.1-fabric-1.114.2.jar
cc_vs-1.20.1-fabric-0.1.1.jar
clockwork-1.20.1-0.1.16-fabric-b3b22e39fe.jar
create-fabric-0.5.1-f-build.1417+mc1.20.1.jar
fabric-api-0.92.2+1.20.1.jar
fabric-language-kotlin-1.12.3+kotlin.2.0.21.jar
Some-Peripherals-0.0.12-fabric.jar
valkyrienskies-120-2.3.0-beta.5.jar
```

The stack trace is quite large, but this snippit captures the failure:

```[21:16:33] [main/WARN]: Error loading class: net/minecraft/class_809$class_811 (java.lang.ClassNotFoundException: net/minecraft/class_809$class_811)
[21:16:33] [main/WARN]: Error loading class: net/minecraft/class_1059$class_4007 (java.lang.ClassNotFoundException: net/minecraft/class_1059$class_4007)
[21:16:33] [main/WARN]: Error loading class: net/minecraft/class_1058$class_5790 (java.lang.ClassNotFoundException: net/minecraft/class_1058$class_5790)
[21:16:33] [main/WARN]: Error loading class: net/minecraft/class_2708$class_2709 (java.lang.ClassNotFoundException: net/minecraft/class_2708$class_2709)
[21:16:33] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[21:16:33] [main/INFO]: Instancing error handler class org.valkyrienskies.mod.mixin.ValkyrienMixinErrorHandler
[21:16:33] [main/ERROR]: Mixin apply for mod porting_lib failed porting_lib.mixins.common.json:LevelMixin from mod porting_lib -> net.minecraft.class_1937: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method method_8488 in porting_lib.mixins.common.json:LevelMixin from mod porting_lib was not located in the target class net.minecraft.class_1937. Using refmap porting_lib-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method method_8488 in porting_lib.mixins.common.json:LevelMixin from mod porting_lib was not located in the target class net.minecraft.class_1937. Using refmap porting_lib-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:436) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:412) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
```

**Comment by onehittoaster** [comment]
Per discord chat just now, SpaceEye suggests updating the "porting library" version and recompiling.

Looks like it is this line: https://github.com/xiewuzhiying/Some-Peripherals/blob/b88528c1a1660f89a06176a1878e87cf26805caf/fabric/build.gradle#L56

**Comment by Real-Luxof** [comment]
To what exactly did you update the "porting library" version to? I'm trying to compile this from source as well.

**Comment by KSUhippiebus** [comment]
Did anyone ever find fix for this
